title: "岩田 伸治 / Shinji Iwata"
description: "Mail : iwata_shinji@cyberagent.co.jp<br>[X(Twitter)](https://twitter.com/siwata_2023)"
show_downloads: false
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
